version: '3'

services:
  instacart:
    build: .
    container_name: instacart-data-collection
    env_file:
      - .env
    links:
      - database

  database:
    env_file:
      - .db.env
    image: postgres:11.3-alpine
    container_name: instacart-postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/

volumes:
  pgdata:
